package com.rkcoding.expensetrackerapplication.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val LightBlue500 = Color(0xFF03A9F4)
val Grey100 = Color(0xFFF5F5F5)
val DeepPurple900 = Color(0xFF311B92)
val DeepPurple300 = Color(0xFF9575CD)
val Indigo900 = Color(0xFF1A237E)
val Amber500 = Color(0xFFFFC107)
val GreenAlpha700 = Color(0xFF00C853)
val Green200 = Color(0xFFc8e6c9)
val Red500 = Color(0xFFf44336)
val Red200 = Color(0xFFEF9A9A)
val White = Color(0xFFFFFFFF)
val Black = Color(0xFF000000)
val LightBlack = Color(0xFF0F0F0F)

val GridButtonWhite = Color(0xFFE2E7EF)
val GridBorderGray = Color(0xFFBBCAD0)

val food_drink = Color(0xFF86DEB7)
val healthBg = Color(0xFF235789)
val businessBg = Color(0xFFF2BEFC)
val travelBg = Color(0xFFADEEE3)
val taxiBg = Color(0xFF083D77)
val leisureBg = Color(0xFFEABF1F)
val snackBg = Color(0xFFEE964B)
val giftBg = Color(0xFFF95738)
val petBg = Color(0xFFF4D35E)
val miscBg = Color(0xFF323031)
val subBg = Color(0xFFDF367C)
val gadgetBg = Color(0xFF4C3549)
val vehicleBg = Color(0xFF2E4052)
val clothBg = Color(0xFFFFFC85)
val electricBg = Color(0xFFB8F3FF)
val homeBg = Color(0xFFFFC0BE)
val schBg = Color(0xFF7F95D1)
val groceryBg = Color(0xFF61C9A8)

val purple = Color(0xFF6733C4)
val Green = Color(0xFF219425)

val md_theme_light_primary = Color(0xFF855BC5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFECDCFF)
val md_theme_light_onPrimaryContainer = Color(0xFF280056)
val md_theme_light_secondary = Color(0xFF645A70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEBDEF7)
val md_theme_light_onSecondaryContainer = Color(0xFF1F182A)
val md_theme_light_tertiary = Color(0xFF724C9E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEFDBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF2B0053)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE8E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF4A454E)
val md_theme_light_outline = Color(0xFF7B757F)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFF4)
val md_theme_light_inverseSurface = Color(0xFF322F33)
val md_theme_light_inversePrimary = Color(0xFFD6BAFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6E4DA0)
val md_theme_light_outlineVariant = Color(0xFFCBC4CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFC29CFA)
val md_theme_dark_onPrimary = Color(0xFF3E1C6F)
val md_theme_dark_primaryContainer = Color(0xFF563587)
val md_theme_dark_onPrimaryContainer = Color(0xFFECDCFF)
val md_theme_dark_secondary = Color(0xFFCEC2DB)
val md_theme_dark_onSecondary = Color(0xFF352D40)
val md_theme_dark_secondaryContainer = Color(0xFF4C4357)
val md_theme_dark_onSecondaryContainer = Color(0xFFEBDEF7)
val md_theme_dark_tertiary = Color(0xFFDAB9FF)
val md_theme_dark_onTertiary = Color(0xFF421A6C)
val md_theme_dark_tertiaryContainer = Color(0xFF593484)
val md_theme_dark_onTertiaryContainer = Color(0xFFEFDBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B1E)
val md_theme_dark_onBackground = Color(0xFFE7E1E6)
val md_theme_dark_surface = Color(0xFF1D1B1E)
val md_theme_dark_onSurface = Color(0xFFE7E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF4A454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCBC4CF)
val md_theme_dark_outline = Color(0xFF958E99)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE7E1E6)
val md_theme_dark_inversePrimary = Color(0xFF6E4DA0)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFD6BAFF)
val md_theme_dark_outlineVariant = Color(0xFF4A454E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFD4BCF5)
